### ISSUE TITLE
Spotify API

### ISSUE THREAD

**Issue by gmejia87** [wilmr/Music-en-Vivo#5]
##Goal
To provide a link to the artist's Spotify page for the user to explore their music. 

##Requirements
* Link clearly visible
* Functionality of the link

##Potential Issues
* Link doesn't load
* Link doesn't work

**Comment by rnhamlin** [comment]
We attempted to use Spotify API, but decided to change directions with the web app, so we're closing this because we no longer need Spotify API.

**Comment by gmejia87** [comment]
Spotify was in the works, had some issues connecting it to the html. However, after the presentation and getting user feedback, we opted to go with a different api for a more user friendly function. Hence this issue is now closed.
